baseURL = "https://freboch.github.io/CSS_project_website"
title = "Harry Potter and the Networks of Analysis"
description = "Harry Potter University Project"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Anne Sophie Høtbjerg Hansen", "Frederikke B. Christensen", "Kirstine Cort Graae"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/freboch/CSS_project_website"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Word Clouds"
        link = "/word-clouds"
    [[params.nav]]
        label = "Sentiment Analysis"
        link = "/sentiment-analysis"

