baseURL = "https://freboch.github.io/CSS_project_website"
title = "Home Page"
label = 'Home Page'
description = "Harry Potter University Project"
relativeURLs = true
theme = 'theme'

[params]
    authors = ["Anne Sophie H. Hansen", "Frederikke B. Christensen", "Kirstine Cort Graae"]
    notebook = "/Explainer_Notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/freboch/CSS_project_website"
    logo = '/images/favicon.png'
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Word Clouds"
        link = "/word-clouds"
    [[params.nav]]
        label = "Sentiment Analysis"
        link = "/sentiment-analysis"

